# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := tlmm tlmm-lite tests

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

tlmm: 
	@echo "==== Building tlmm ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tlmm.make

tlmm-lite: 
	@echo "==== Building tlmm-lite ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tlmm-lite.make

tests: tlmm
	@echo "==== Building tests ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tests.make

clean:
	@${MAKE} --no-print-directory -C . -f tlmm.make clean
	@${MAKE} --no-print-directory -C . -f tlmm-lite.make clean
	@${MAKE} --no-print-directory -C . -f tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tlmm"
	@echo "   tlmm-lite"
	@echo "   tests"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
